### ISSUE TITLE
ENHANCEMENT: Support Greasemonkey and Tampermonkey

### ISSUE THREAD

**Issue by 23maverick23** [Cacodaimon/GhostText-for-SublimeText#64]
**Overview:**
Allow GhostText to open up SublimeText to edit scripts in Greasemonkey or Tampermonkey extensions.

**Usage:**
Instead of writing scripts in a console window or a basic editor, scripts can be written in ST which allows for better syntax highlighting, better autocomplete, better linting preferences and ultimately better user experience.

**Details:**
Greasemonkey in Firefox uses the MDN [Scratchpad](https://developer.mozilla.org/en-US/docs/Tools/Scratchpad) feature, which isn't available to GhostText.
Tampermonkey in Chrome opens in an extension-specific URL page with a code editor (which throws an error in the `background.html` page)

```bash
extensions::uncaught_exception_handler:8 Error in response to tabs.executeScript: TypeError: Cannot read property '0' of undefined
    at Object.callback (chrome-extension://godiecgffnchndlihlpaajjcplehddca/scripts/lib.js:65:29)
    at Object.GhostText.loadContentJs (chrome-extension://godiecgffnchndlihlpaajjcplehddca/scripts/lib.js:62:21)
    at toggleConnection (chrome-extension://godiecgffnchndlihlpaajjcplehddca/scripts/lib.js:91:27)
    at Object.callback (chrome-extension://godiecgffnchndlihlpaajjcplehddca/scripts/lib.js:35:13)handler @ extensions::uncaught_exception_handler:8

extensions::lastError:133 Unchecked runtime.lastError while running tabs.executeScript: Cannot access a chrome-extension:// URL of different extension
    at Object.GhostText.loadContentJs (chrome-extension://godiecgffnchndlihlpaajjcplehddca/scripts/lib.js:62:21)
    at toggleConnection (chrome-extension://godiecgffnchndlihlpaajjcplehddca/scripts/lib.js:91:27)
    at Object.callback (chrome-extension://godiecgffnchndlihlpaajjcplehddca/scripts/lib.js:35:13)
```

**Comment by bfred-it** [comment]
[Unfortunately can't](https://github.com/Cacodaimon/GhostText-for-SublimeText/issues/55)
